import{a as w,S,i as o}from"./assets/vendor-ee72e1a4.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&n(u)}).observe(document,{childList:!0,subtree:!0});function i(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(t){if(t.ep)return;t.ep=!0;const s=i(t);fetch(t.href,s)}})();async function m(e,r){const i="https://pixabay.com/api/",n=new URLSearchParams({key:"44038258-5ed49f7c308af682a7282867b",q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:r});try{return(await w.get(i,{params:n})).data}catch(t){throw new Error(t.message)}}const q=document.querySelector(".js-images-container");function v(e){return`<li class='image-gallery'>
    <a href="${e.largeImageURL}" class="gallery-list">
      <img src="${e.webformatURL}" 
           alt="${e.tags}" loading="lazy"
           class="gallery-link"/>
           </a>
      <div class="info-list">
        <p class="info-item"><b class info-title>Likes:</b> ${e.likes}</p>
        <p class="info-item"><b class info-title>Views:</b> ${e.views}</p>
        <p class="info-item"><b class info-title>Comments:</b> ${e.comments}</p>
        <p class="info-item"><b class info-title>Downloads:</b> ${e.downloads}</p>
      </div>
      </li>
      `}function E(e){return e.map(v).join("")}function y(e){const r=E(e);q.insertAdjacentHTML("beforeend",r),new S(".gallery, a",{captionsData:"alt",captionDelay:250}).refresh()}const f=document.querySelector(".images-form"),g=document.querySelector(".loader"),P=document.querySelector(".js-images-container"),c=document.querySelector(".load-more");let a=1,l="";const d=15;let h=0;f.addEventListener("submit",async e=>{if(e.preventDefault(),P.innerHTML="",l=e.target.elements.query.value.trim(),a=1,!l){o.error({title:"Error",message:"Please enter a search query"});return}b();try{const r=await m(l,a,d);r.hits.length>0?(h=Math.ceil(r.totalHits/d),y(r.hits),p()):o.warning({title:"Warning",message:"Sorry, there are no images matching your search query. Please try again!"})}catch(r){o.error({title:"Error",message:r.message})}finally{L()}f.reset()});c.addEventListener("click",async()=>{a+=1,b();try{const e=await m(l,a,d);e.hits.length>0?(y(e.hits),p(),$()):(c.style.display="none",o.info({title:"Info",message:"We're sorry, but you've reached the end of search results."}))}catch(e){o.error({title:"Error",message:e.message})}finally{L()}});function p(){a>=h?(c.style.display="none",o.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})):c.style.display="block"}function b(){g.style.display="block"}function L(){g.style.display="none"}function $(){const{height:e}=document.querySelector(".js-images-container").firstElementChild.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=commonHelpers.js.map
