import{a as L,S as w,i as n}from"./assets/vendor-ee72e1a4.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&i(l)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();async function m(e,r){const s="https://pixabay.com/api/",i=new URLSearchParams({key:"44038258-5ed49f7c308af682a7282867b",q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",per_page:15,page:r});try{return(await L.get(s,{params:i})).data}catch(t){throw new Error(t.message)}}const q=document.querySelector(".js-images-container");function E(e){return`<li class='image-gallery'>
    <a href="${e.largeImageURL}" class="gallery-list">
      <img src="${e.webformatURL}" 
           alt="${e.tags}" loading="lazy"
           class="gallery-link"/>
           </a>
      <div class="info-list">
        <p class="info-item"><b class info-title>Likes:</b> ${e.likes}</p>
        <p class="info-item"><b class info-title>Views:</b> ${e.views}</p>
        <p class="info-item"><b class info-title>Comments:</b> ${e.comments}</p>
        <p class="info-item"><b class info-title>Downloads:</b> ${e.downloads}</p>
      </div>
      </li>
      `}function S(e){return e.map(E).join("")}function h(e){const r=S(e);q.insertAdjacentHTML("beforeend",r),new w(".gallery, a",{captionsData:"alt",captionDelay:250}).refresh()}const f=document.querySelector(".images-form"),y=document.querySelector(".loader"),v=document.querySelector(".js-images-container"),d=document.querySelector(".load-more");let a=1,P="",g=0;d.addEventListener("click",M);f.addEventListener("submit",async e=>{e.preventDefault(),u(),v.innerHTML="",b();const r=e.target.elements.query.value.trim();if(!r){n.error({title:"Error",message:"Please enter a search query"}),c();return}try{a=1;const s=await m(r,a);if(s.hits.length>0)h(s.hits),g=Math.ceil(s.totalHits/15),p();else throw Error("Sorry, there are no images matching your search query. Please try again!")}catch(s){n.error({title:"Error",message:s.message})}finally{c()}f.reset()});async function M(){b(),u();try{a+=1;const e=await m(P,a);if(e.hits.length>0){h(e.hits),p();const r=document.querySelector(".js-images-container").getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"});return}else throw new Error("We're sorry, there are no more posts to load")}catch{n.error({title:"Error",message:"Failed to fetch images. Please try again later."})}finally{c()}}function p(){g>a?$():(u(),n.error({title:"Error",message:"We're sorry, but you've reached the end of search results."}))}function b(){y.style.display="block"}function c(){y.style.display="none"}function $(){d.classList.remove("hidden")}function u(){d.classList.add("hidden")}
//# sourceMappingURL=commonHelpers.js.map
